# Generated by Django 5.2.7 on 2026-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_dishvarietysection_dishvarietyoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/%Y/%m/%d/'),
        ),
    ]
