# Generated by Django 5.2.7 on 2026-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dishimage_image_url_dishimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(default='dishes/dish_zldtcj.jpg', upload_to='dishes/%Y/%m/%d/'),
        ),
    ]
