# Generated by Django 5.2.7 on 2026-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_dishimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dljw6q0yq/image/upload/v1777041912/dish_zldtcj.jpg', upload_to='dishes/%Y/%m/%d/'),
        ),
    ]
