# Generated by Django 5.2.7 on 2026-04-24 20:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_dishimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dljw6q0yq/image/upload/v1777041912/dish_zldtcj.jpg', max_length=255, verbose_name='Dish Image'),
        ),
    ]
