# Generated by Django 5.2.7 on 2026-01-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='dietary_preferences',
        ),
    ]
