# Generated by Django 5.2.7 on 2026-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_profile_picture_url_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the chef is currently available to accept orders'),
        ),
    ]
