# Generated by Django 5.2.7 on 2026-04-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_chef_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profiles/profilepicture_mae8dg.jpg', upload_to='profiles/'),
        ),
    ]
