# Generated by Django 5.2.7 on 2026-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='https://res.cloudinary.com/dljw6q0yq/image/upload/v1777041924/profilepicture_mae8dg.jpg', upload_to='profiles/'),
        ),
    ]
