# Generated by Django 5.2.7 on 2026-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=12, null=True),
        ),
    ]
