# Generated by Django 5.2.7 on 2026-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
    ]
