# Generated by Django 5.2.7 on 2026-04-21 21:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dishimage_image_url_dishimage_image'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='chef_name_snapshot',
            field=models.CharField(default='', help_text='Chef name at order time', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_preparation_minutes',
            field=models.PositiveIntegerField(default=0, help_text="Calculated from ordered dishes' preparation times"),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chef_name_snapshot',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish_base_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish_name_snapshot',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=12, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(limit_choices_to={'chef__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'consumer__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.dish'),
        ),
        migrations.CreateModel(
            name='OrderItemVarietySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text="Section name snapshot (e.g., 'Size Options')", max_length=100)),
                ('option_name', models.CharField(help_text="Option name snapshot (e.g., 'Large')", max_length=100)),
                ('option_price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment at order time', max_digits=6)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variety_selections', to='orders.orderitem')),
            ],
            options={
                'ordering': ['section_name', 'option_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_accepted', 'Order Accepted'), ('order_rejected', 'Order Rejected'), ('order_cancelled', 'Order Cancelled'), ('preparation_reminder', 'Preparation Reminder'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
